# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b810f51fcd96b4e28c824386dce6f2a2"
name = "Peter Solberg Bundle"
handle = "peter-solberg-bundle"
application_url = "https://corresponding-cannon-cards-wagon.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory"

[auth]
redirect_urls = ["https://corresponding-cannon-cards-wagon.trycloudflare.com/auth/callback", "https://corresponding-cannon-cards-wagon.trycloudflare.com/auth/shopify/callback", "https://corresponding-cannon-cards-wagon.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://corresponding-cannon-cards-wagon.trycloudflare.com"
subpath = "bbg"
prefix = "apps"

[pos]
embedded = false
